name: Build

on:
  release:
    types: [published]
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/${{ steps.version.outputs.version }}/g' custom_components/scheduler/manifest.json
          cat custom_components/scheduler/manifest.json
          zip scheduler.zip -r custom_components/scheduler/

      - uses: actions/upload-artifact@v2
        with:
          name: scheduler
          path: scheduler.zip
