name: Build

on:
  release:
    types: [published]
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Run a multi-line script
        run: |
          echo ${{ steps.version.outputs.version }}
          cat custom_components/scheduler/manifest.json
          sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' custom_components/scheduler/manifest.json
          cat custom_components/scheduler/manifest.json
